import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AddForm from '../components/AddForm';
import ProjectList from '../components/ProjectList';
import { server } from '../config';
import { getSession } from 'next-auth/react';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export default function Home({ getProject, session }) {
  const [ projects, setProjects ] = useState(getProject);

  return (
    <div className={styles.container}>
      <Head>
        <title>Project Managament Tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Project Management Tool
        </h1>
        <h6 className={styles.subheading}>Manage all your projects with ease.</h6>
        <AddForm projects = { projects }setProjects = { setProjects } />
        <ProjectList projects={ projects } setProjects = { setProjects }/>
      </main>
    </div>
  )
}
export async function getServerSideProps(context) {
  const session = await getSession(context);
  const getProject = await prisma.project.findMany({
    where :{
      user : {
        email: session.user.email
      }
    }
  })
  return {
    props: { getProject, session }, // will be passed to the page component as props
  }
}